//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClassroomAllocationSystemEntities : DbContext
    {
        public ClassroomAllocationSystemEntities()
            : base("name=ClassroomAllocationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<BookRoom> BookRooms { get; set; }
        public virtual DbSet<ClassRoom> ClassRooms { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserQuestionDetail> UserQuestionDetails { get; set; }
        public virtual DbSet<UserRegistrationDetail> UserRegistrationDetails { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ClassRoomDetail> ClassRoomDetails { get; set; }
    
        public virtual ObjectResult<GetFeedback_Result> GetFeedback()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFeedback_Result>("GetFeedback");
        }
    }
}
